version: '3.9'

services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exampledb
    ports:
      - '5432:5432'
